# fly.toml app configuration file generated for home-gateway on 2023-11-20T20:19:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "home-gateway"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[deploy]
  strategy = "immediate"

[env]
  GOGC = 10


[[services]]
  protocol = "tcp"
  internal_port = 80

  [services.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 1000

  [[services.ports]]
    port = 80

[[services]]
  protocol = "tcp"
  internal_port = 443

  [services.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 1000

  [[services.ports]]
    port = 443

[[services]]
  protocol = "udp"
  internal_port = 443

  [services.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 1000

  [[services.ports]]
    port = 443

[[restart]]
  policy = "on-failure"
  retries = 10
  processes = ["tailscaled"]
